AWSTemplateFormatVersion: '2010-09-09'
Description: 'Terraform Backend Resources - S3 Bucket and DynamoDB Table for State Management'

Parameters:
  ProjectName:
    Type: String
    Default: receiptly
    Description: Project name for resource naming

Resources:
  # S3 Bucket for Terraform State
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-terraform-state'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Purpose
          Value: TerraformState

  # S3 Bucket Policy
  TerraformStateBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TerraformStateBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt TerraformStateBucket.Arn
              - !Sub '${TerraformStateBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': false

  # DynamoDB Table for State Locking
  TerraformLockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-terraform-locks'
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Purpose
          Value: TerraformStateLocking

Outputs:
  StateBucketName:
    Description: S3 bucket name for Terraform state
    Value: !Ref TerraformStateBucket
    Export:
      Name: !Sub '${ProjectName}-terraform-state-bucket'

  StateBucketArn:
    Description: S3 bucket ARN for Terraform state
    Value: !GetAtt TerraformStateBucket.Arn
    Export:
      Name: !Sub '${ProjectName}-terraform-state-bucket-arn'

  LockTableName:
    Description: DynamoDB table name for Terraform state locking
    Value: !Ref TerraformLockTable
    Export:
      Name: !Sub '${ProjectName}-terraform-lock-table'

  LockTableArn:
    Description: DynamoDB table ARN for Terraform state locking
    Value: !GetAtt TerraformLockTable.Arn
    Export:
      Name: !Sub '${ProjectName}-terraform-lock-table-arn'
